substitutions:
  device_name: esp-03     #   Speis

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "DmH8pl4LtKPiyBAOXaOYWgBLM8O2UJTuYXrO9EbhTJE="

ota:
  - platform: esphome
    password: "33fb1fafdea7169cda8a4c7c9e4af71f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${device_name} Hotspot"
    password: "tXr1MCl61gw2"

captive_portal:

mqtt:
  broker: 10.0.0.10
  username: mqtt
  password: mqtt
  discovery: false

i2c:
  - id: bus_a
    sda: GPIO4
    scl: GPIO5
    scan: true

mcp23017:
  - id: i2c_expand07
    address: 0x20
    i2c_id: bus_a


button:
  - platform: restart
    name: '${device_name} Restart'
    internal: false

sensor:
  - platform: wifi_signal
    name: "WiFi Signal ${device_name}"
    update_interval: 60s

  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temp Speis"
      filters:
       - offset: -0.3
    humidity:
      name: "Humidity Speis"
      filters:
       - offset: 7
    update_interval: 60s

  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Temp K Vorraum"
      filters:
       - offset: 0.4
    humidity:
      name: "Humidity K Vorraum"
      filters:
       - offset: 2
    update_interval: 50s


binary_sensor:

                              #   P I R

  - platform: gpio
    name: "pir02"
    id: pir02
    icon: mdi:motion-sensor
    pin:
      mcp23xxx: i2c_expand07
      number: 0
    device_class: motion

                            # Schalter

  - platform: gpio
    name: "bin_sens_49"
    id: bin_sens_49
    pin:
      mcp23xxx: i2c_expand07
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_state:
      - mqtt.publish:
           topic: "esp32-02/switch/i2c_relay05_sw05/command"
           payload: "TOGGLE"      


  - platform: gpio
    name: "bin_sens_50"
    id: bin_sens_50
    pin:
      mcp23xxx: i2c_expand07
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_press:
      then:
        - mqtt.publish:
            topic: "dimmer/dimm_script02"
            payload: "pressed02"
    on_release:
      then:
        - mqtt.publish:
            topic: "dimmer/dimm_script02"
            payload: "released02"


  - platform: gpio
    name: "bin_sens_51"
    id: bin_sens_51
    pin:
      mcp23xxx: i2c_expand07
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_press:
      - mqtt.publish:
           topic: "esp32-02/switch/i2c_relay05_sw06/command"
           payload: "TOGGLE" 

  - platform: gpio
    name: "bin_sens_52"
    id: bin_sens_52
    pin:
      mcp23xxx: i2c_expand07
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_press:
      then:
        - mqtt.publish:
            topic: "dimmer/dimm_script03"
            payload: "pressed03"
    on_release:
      then:
        - mqtt.publish:
            topic: "dimmer/dimm_script03"
            payload: "released03"

  - platform: gpio
    name: "bin_sens_53"
    id: bin_sens_53
    pin:
      mcp23xxx: i2c_expand07
      number: 5
      mode:
        input: true
        pullup: true
      inverted: false
    device_class: light
    on_state:
      - mqtt.publish:
           topic: "esp32-02/switch/i2c_relay05_sw03/command"
           payload: "TOGGLE" 


  - platform: gpio
    name: "bin_sens_54"
    id: bin_sens_54
    pin:
      mcp23xxx: i2c_expand07
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_press:
      - mqtt.publish:
           topic: "esp32-02/switch/i2c_relay05_sw01/command"
           payload: "TOGGLE" 

  - platform: gpio
    name: "bin_sens_55"
    id: bin_sens_55
    pin:
      mcp23xxx: i2c_expand07
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_press:
      then:
        - mqtt.publish:
            topic: "dimmer/dimm_script02"
            payload: "pressed02"
    on_release:
      then:
        - mqtt.publish:
            topic: "dimmer/dimm_script02"
            payload: "released02"

  - platform: gpio
    name: "bin_sens_56"
    id: bin_sens_56
    pin:
      mcp23xxx: i2c_expand07
      number: 8
      mode:
        input: true
        pullup: true
      inverted: false
    device_class: light
    on_state:
      - mqtt.publish:
           topic: "esp32-02/switch/i2c_relay05_sw04/command"
           payload: "TOGGLE" 

  - platform: gpio
    name: "bin_sens_57"
    id: bin_sens_57
    pin:
      mcp23xxx: i2c_expand07
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light


  - platform: gpio
    name: "bin_sens_58"
    id: bin_sens_58
    pin:
      mcp23xxx: i2c_expand07
      number: 10
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_state:
      - mqtt.publish:
           topic: "esp32-02/switch/i2c_relay05_sw06/command"
           payload: "TOGGLE" 
