substitutions:
  device_name: esp-05

esphome:
  name: ${device_name}


esp8266:
  board: d1_mini

logger:
  baud_rate: 0
  level: DEBUG


api:
  encryption:
    key: "CYLuun1/v8gzxp2rhNutFkVBz/Tjq/u7wjAiI6LOdtE="

ota:
  - platform: esphome
    password: "b03c44d0ae92ca2a96b4226cd21e7798"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${device_name} Hotspot"
    password: "pFjqLRL9yGmA"

captive_portal:

button:
  - platform: restart
    name: '${device_name} Restart'
    internal: false 


uart:
  id: uart_dsmr
  rx_pin: 
    number: GPIO13
    inverted: true    
  baud_rate: 115200
  rx_buffer_size: 1700
  debug:
    direction: RX
    after:
      delimiter: "\r\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);


dsmr:
  uart_id: uart_dsmr
  decryption_key: !secret guek
  max_telegram_length: 1700

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Delivered Tariff 1"
      state_class: total_increasing
      accuracy_decimals: 3
    energy_delivered_tariff2:
      name: "Energy Delivered Tariff 2"
      state_class: total_increasing
      accuracy_decimals: 3
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
      unit_of_measurement: kW
    power_delivered_l1:
      name: "power_l1"
      unit_of_measurement: kW
      
  - platform: wifi_signal
    name: "WiFi Signal ${device_name}"
    update_interval: 60s  

text_sensor:
  - platform: dsmr
    identification:
      name: "dsmr_identification"
    p1_version:
      name: "dsmr_p1_version"
    electricity_tariff:
      name: "aktueller Tarif"
    telegram:
      name: "telegram"
